title: Video Holography
author: Jan Genoe
logo: images/logo.png
description: Video Holography ERC project results summary
only_build_toc_files: true
html:
  favicon: images/erc.ico
execute:
  execute_notebooks: 'off'
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https]
latex:
  latex_documents:
     targetname: python.tex
bibtex_bibfiles:
  - VideoHolography.bib
sphinx:
  config:
    html_theme_options:
      repository_url: https://github.com/jangenoe/VideoHolography
      use_issues_button: false
      use_download_button: false
      use_repository_button: false
      use_edit_page_button: false
      home_page_in_toc: true
      logo:
        image_light: images/logo.png
        image_dark: images/logo_negatif.png
    extensions : [
    'sphinx_toolbox.tweaks.latex_layout',
    ]
    html_favicon: images/erc.ico
    html_show_copyright: false
    html_static_path: ['docs']
    nb_remove_code_source: true
    latex_logo: images/logo.png
    latex_elements:
      extraclassoptions: 'openany,oneside'
      papersize: 'a4paper'
      preamble: |+
        \usepackage{etoolbox}
        \AtBeginEnvironment{figure}{\pretocmd{\hyperlink}{\protect}{}{}}  
    bibtex_reference_style: label
    bibtex_default_style : "unsrt"
 