title: Video Holography
author: Jan Genoe
logo: images/logo.png
description: Video Holography ERC project results summary
only_build_toc_files: true
repository:
  url: https://github.com/jangenoe/VideoHolography
html:
  use_issues_button: false
  use_edit_page_button: false
  use_repository_button: false
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution
    - tasklist
bibtex_bibfiles:
  - VideoHolography.bib
sphinx:
  config:
    html_show_copyright: false
    nb_remove_code_source: true
    latex_logo: images/logo.png
    latex_elements:
      extraclassoptions: 'openany,oneside'
      papersize: 'a4paper'
      preamble: |+
        \usepackage{etoolbox}
        \AtBeginEnvironment{figure}{\pretocmd{\hyperlink}{\protect}{}{}}  
    bibtex_reference_style: label
    bibtex_default_style : "unsrt"

